### ISSUE TITLE
变量地址如何使用？

### ISSUE THREAD

**Issue by huanggp56** [byzy/jcv-maven-plugin#11]
我的js文件地址
`<script src="${pageContext.request.contextPath}/js/main/Particleground.js" ></script>`

配置
```
<jsConstantName>\${pageContext.request.contextPath}</jsConstantName>
<cssConstantName>\${pageContext.request.contextPath}</cssConstantName>
```

无效是怎么回事

**Comment by byzy** [comment]
修改这里<jsConstantName>\${pageContext.request.contextPath}/</jsConstantName>，最后添加/
css 同理
