### ISSUE TITLE
js不支持相对路径

### ISSUE THREAD

**Issue by lmm1990** [byzy/jcv-maven-plugin#2]
<script type="text/javascript" src="../internal.js"></script>

**Comment by byzy** [comment]
不知持，因为无法计算当前路径，特别是使用nginx等动静分类项目，就无法直接，说明文档有提到不支持相对路径

注意事项

不支持 ../../xxx.js
不支持 ../../xx.css
如果启用js压缩，那么在js中变量定义禁止使用js关键字
html 清除注释只支持网页中的
插件不会在eclipse中生效，在package后才会生效
注意在使用md5文件名的时候请注意排除一些js动态加载css,如果修改了文件名会导致无法加载到css,因此需要排除掉，目前已知有kindeditor,layer,My97DatePicker
