### ISSUE TITLE
如何验证插件生效?

### ISSUE THREAD

**Issue by jelly-mazic** [byzy/jcv-maven-plugin#5]
前辈你好, 在使用插件过程中有点问题想请教你.
我按照教程用mvn clean package进行打包, 并部署到Tomcat中运行. 我想知道插件生产的md5值在哪里可以看到(之所以想看这个, 是因为发现使用插件后访问的url没有变化)

**Comment by byzy** [comment]
最终页面会生成下面这种
`<link type="text/css" rel="stylesheet" href="/static/css/index.css?version=a89c191e43a3969be214dfd7d07aff90" />`

**Comment by jelly-mazic** [comment]
十分感谢, 但是我刚刚看了下, 自己的页面没有实现上述效果.
可能是自己哪里配置错误了, 我再查一查. 
十分感谢, 大神.
