### ISSUE TITLE
springboot按照示例打包提示404找不到资源

### ISSUE THREAD

**Issue by kyne0116** [byzy/jcv-maven-plugin#6]
普通HTML和thymeleaf的引用方式都像下面：
    <script  src="/static/js/index.js"></script>
    <link type="text/css" rel="stylesheet" href="/static/css/index.css" />
文件物理位置
/resources/static/js/index.js
/resources/static/css/index.css

采用版本SpringBoot 2.0.2.RELEASE，执行mvn clean package -Dmaven.test.skip=true打包启动后，提示
http://localhost:8080/static/js/index.js  404 NOT FOUND。
请帮忙看下问题，谢谢！

**Comment by byzy** [comment]
提供pom ？
