### ISSUE TITLE
js和css文件未处理

### ISSUE THREAD

**Issue by tianwanfeng** [byzy/jcv-maven-plugin#7]
console里提示如下，为啥文件被跳过了，复制的未处理的文件数量倒是没问题，刚好是webapp目录下css+js的数量
`[INFO] find suffixs size:1
[INFO] build sourceEncoding:UTF-8
[INFO] out Dir:E:\\webapp-light
[INFO] system is linux:false
[INFO] css method is :MD5_METHOD
[INFO] js method is :MD5_METHOD
[INFO] build webRootName:webapp-light
[INFO] web app Dir:E:\coding\workspace_yd\webapp-light\src\main\webapp
[INFO] --------------------------------- copy untreated file file size: 14
[INFO] --------------------------------- process success file size: 0`

配置如下：
`<plugin>
				<groupId>com.iqarr.maven.plugin</groupId>
				<artifactId>jcv-maven-plugin</artifactId>
				<version>0.0.6</version>
					<executions>
						<execution>
						<id>process</id>
						<phase>package</phase>
							<goals>
								<goal>process</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						
						<suffixs>
							<param>html</param>
						</suffixs>
						<outputDirectory>E:/</outputDirectory>
						<globaJsMethod>MD5_METHOD</globaJsMethod>
						<globaCssMethod>MD5_METHOD</globaCssMethod>
						
						<compressionJs>true</compressionJs>
						
						<compressionCss>true</compressionCss>
					</configuration>
			</plugin>`

**Comment by byzy** [comment]
可能原因:
1. js 的引用是否使用了`../../xxx.js`，对于这种方式是不支持.
2. js css 后缀为min.js 这个可以在参数中覆盖.

建议贴上js css引用代码,方便追踪文件
看到你的`outputDirectory`配置是错误的，如果你是要打包war的话建议不要配置该参数

**Comment by tianwanfeng** [comment]
outputDirectory我加这个是为了看输出方便点，引用方式，比如这样

> <link rel="stylesheet" href="/static/css/recommend.css">
    <script src="/static/js/util.js"></script>
    <script src="/static/lib/echo.js"></script>
    <script src="/static/lib/react.js"></script>
    <script src="/static/lib/react-dom.js"></script>
    <script src="/static/lib/browser.min.js"></script>
    <script src="/static/lib/jquery.min.js"></script>

**Comment by byzy** [comment]
@tianwanfeng 

那么检查你js 路径是不是在`E:\coding\workspace_yd\webapp-light\src\main\webapp\static\js\*.js`
js的寻址路径就是以webapp为root路径。
如果目录正确，建议提供pom还有文件结构,或者使用`mvn -X package` 提供日志

**Comment by tianwanfeng** [comment]
目录肯定是没问题的，毕竟页面引用都正常。我发现即使我配了html和jsp两个后缀，find suffixs size:1 这个一直输出的是1。因为我之前所有页面都是html的，后来我加了个空的jsp，里面引用了相同的js和css，这时候打包后就可以看到这个jsp里关于js和css的引用就变成追加md5的正确格式。是我这个suffixs参数配置不对么？
![qq 20170509132356](https://cloud.githubusercontent.com/assets/7778999/25836598/cb473800-34ba-11e7-9f7c-62cfaefa5fb6.jpg)，=

**Comment by byzy** [comment]
默认值只处理jsp,你的问题应该是配置参数没有生效，你使用 的是什么版本的maven，或者你直接用命令行`mvn -X clean package` 看看
```
   /**
     * 默认检查文件后缀
     */
    @Parameter(defaultValue ="jsp")
    private List<String> suffixs;
```
@tianwanfeng

**Comment by tianwanfeng** [comment]
我看package输出显示的版本是3.0.4，附件是-x package 的console输出
[log.txt](https://github.com/byzy/jcv-maven-plugin/files/985695/log.txt)

**Comment by byzy** [comment]
建议升级maven 我在官网都没看到`3.0.4`,最老的版本也是`3.0.5`，可能你的那个版本不支持list值,建议你升级maven 3.3以上.  详细见 [maven](https://maven.apache.org/download.cgi) [maven dowload](http://apache.claz.org/maven/maven-3/)
正常下debug下应该看到如下:
```
[DEBUG]   (f) sourceEncoding = UTF-8
[DEBUG]   (f) suffixs = [html, jsp]
[DEBUG]   (f) userCompressionSuffix = min
```
@tianwanfeng
